name: Wrongler
filename: wrongler.js
license: Public domain, http://unlicense.org
copyright: Koppel Andrey
author: lastdrop
category: Interface
sources:
  - Source/Wrongler.js
  - Source/Widget.js
  - Source/Widget/Body.js
  - Source/Widget/Input.js
  - Source/Application.js